BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS Alunos (
    id INTEGER PRIMARY KEY,
    nome TEXT NOT NULL,
    idade INTEGER,
    turma TEXT,
    nota REAL
, cidade TEXT);
CREATE TABLE IF NOT EXISTS Disciplinas (
    id INTEGER PRIMARY KEY,
    disciplina TEXT NOT NULL,
    professor TEXT,
    carga_horaria INTEGER,
    laboratorio TEXT
	);
INSERT INTO "Alunos" ("id","nome","idade","turma","nota","cidade") VALUES (1,'Ana Souza',20,'Info A',9.0,'Recife'),
 (2,'Bruno Lima',20,'Administração A',7.0,'Olinda'),
 (3,'Carla Santos',18,'Info A',9.2,'Jaboatão dos Guararapes'),
 (4,'Diego Alves',22,'Info B',6.8,'Paulista'),
 (5,'Elisa Rocha',21,'Administração A',8.9,'Recife'),
 (6,'Felipe Melo',20,'Redes A',7.2,NULL),
 (7,'Gabriela Costa',19,'Info A',9.7,NULL),
 (9,'Igor Martins',18,'Info B',8.1,NULL),
 (10,'Joana Ferreira',19,'Redes A',7.8,NULL),
 (11,'Lucas Pereira',21,'Administração A',6.5,NULL),
 (12,'Mariana Lopes',20,'Info A',9.4,NULL),
 (14,'Olívia Ramos',18,'Info A',8.3,NULL),
 (15,'Paulo Mendes',20,'Redes A',7.1,NULL),
 (16,'Renata Lima',19,'Administração A',9.0,NULL),
 (17,'Samuel Barros',21,'Info B',4.9,NULL),
 (18,'Tatiana Nunes',22,'Administração B',6.2,NULL),
 (19,'Vinícius Araújo',20,'Redes B',8.8,NULL),
 (20,'Wesley Cardoso',19,'Info B',5.4,NULL),
 (21,'Aline Monteiro',18,'Administração B',7.6,NULL),
 (22,'Beatriz Cavalcanti',20,'Info A',9.1,NULL),
 (23,'Caio Dantas',23,'Redes B',4.3,NULL),
 (24,'Daniela Freitas',21,'Administração A',8.0,NULL),
 (25,'Eduardo Tavares',19,'Info B',6.9,NULL),
 (26,'Fernanda Queiroz',18,'Redes A',7.9,NULL),
 (27,'Gustavo Moura',22,'Administração B',5.8,NULL),
 (28,'Helena Paiva',20,'Info A',9.6,NULL),
 (29,'Isabela Castro',19,'Redes B',8.4,NULL),
 (30,'José Roberto',24,'Administração A',6.0,NULL),
 (31,'Karen Albuquerque',18,'Info B',7.3,NULL),
 (33,'Mônica Ribeiro',20,'Administração B',8.7,NULL),
 (34,'Natália Pires',19,'Info A',5.1,NULL),
 (35,'Otávio Correia',22,'Redes B',7.7,NULL),
 (36,'Priscila Andrade',21,'Administração A',9.3,NULL),
 (37,'Rafael Batista',20,'Info B',6.7,NULL),
 (38,'Sabrina Oliveira',18,'Redes A',8.2,NULL),
 (39,'Thiago Moreira',23,'Administração B',4.7,NULL),
 (40,'Vitória Fernandes',19,'Info A',9.8,NULL),
 (45,'Nicolas Gomes',22,'Redes A',4.8,NULL),
 (46,'Welington Lima',51,'Info A',9.8,NULL);
INSERT INTO "Disciplinas" ("id","disciplina","professor","carga_horaria","laboratorio") VALUES (1,'Banco de Dados','Marcos Lima',80,'Laboratório 1'),
 (2,'Programação Web','Fernanda Oliveira',80,'Laboratório 2'),
 (3,'Redes de Computadores','Carlos Souza',60,'Laboratório de Redes'),
 (4,'Lógica de Programação','Patrícia Gomes',80,'Laboratório 1'),
 (5,'Engenharia de Software','Rafael Melo',60,NULL),
 (6,'Segurança da Informação','André Barros',60,NULL),
 (7,'Sistemas Operacionais','Luciana Freire',60,NULL),
 (8,'Empreendedorismo','Renato Vasconcelos',40,NULL),
 (9,'Fundamentos de Administração','Camila Torres',60,NULL),
 (10,'Projeto Integrador','Fernanda Oliveira',100,NULL);
COMMIT;
